### ISSUE TITLE
actionの実装

### ISSUE THREAD

**Issue by HiroRittsu** [rionehome/move#2]
# 概要
topicによる操作はやや複雑になってしまうため、actionの実装をする

# 対象
amount.cpp
amount.hpp

**Comment by nakano16180** [comment]
もうちょい詳しく

**Comment by HiroRittsu** [comment]
# 入出力
float64 distance
float64 angle

# 受け取り時
callback関数内で以下のプログラムを記述
        this->move_flag = true;
        this->sensor_angle = 0;
        this->target_distance = msg->distance; 　＜ー”float64 distance”のメッセージ
        this->target_angle = msg->angle;　＜ー”float64 angle”のメッセージ
        this->initial_x = this->sensor_x;
        this->initial_y = this->sensor_y;
        this->last_q_w = this->sensor_q_w;
        this->last_q_z = this->sensor_q_z;

# アクションの終了
amount.cppの93行目の分岐をもってアクションを返す

**Comment by nakano16180** [comment]
## action msg
- 入力
  - float64 distance
  - float64 angle
- 途中経過
  - 考え中
- 結果
  - bool result

## action server function
Amount::amount_update()を使う
